version: '3.8'

services:
  flask1:
    build: ./app
    container_name: flask_app_1
    networks:
      - lb_net

  flask2:
    build: ./app
    container_name: flask_app_2
    networks:
      - lb_net

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask1
      - flask2
    networks:
      - lb_net

networks:
  lb_net:
