version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend_net

  node-app:
    build: ./backend
    container_name: node_app
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb
    networks:
      - backend_net

volumes:
  mongo_data:

networks:
  backend_net:

# run : docker-compose up --build
