version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elk-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk-net

volumes:
  esdata:

networks:
  elk-net:

# run: docker-compose up --build

# Elasticsearch: Truy cập qua http://localhost:9200

# Kiểm tra Elasticsearch hoạt động bằng cách gửi yêu cầu GET:
# curl -u elastic:your_password_here http://localhost:9200

# Kibana: Truy cập qua http://localhost:5601

# Bạn sẽ thấy giao diện Kibana, nơi bạn có thể cấu hình và giám sát Elasticsearch.

