# Cấu hình Redis
bind 0.0.0.0        # Cho phép kết nối từ mọi địa chỉ IP
port 6379           # Cổng mà Redis sẽ lắng nghe
maxmemory 256mb     # Giới hạn bộ nhớ tối đa Redis có thể sử dụng
appendonly yes      # Bật chế độ ghi log append-only file
