version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    command: flask run --host=0.0.0.0
    environment:
      FLASK_ENV: development

  tests:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/app
    command: pytest

#  run: docker-compose -f docker-compose-dev.yml up --build
