spring.application.name=discovery-server
server.port=8761

# Don't register server with itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=discovery-server

# Enable all Actuator endpoints for monitoring
management.endpoints.web.exposure.include=*